version: '3.8'

services:
  postgres:
    image: postgres
    container_name: projeto-biblioteca
    environment:
      - POSTGRES_PASSWORD=0987
    ports:
      - "5432:5432"
    restart: unless-stopped